### ISSUE TITLE
Brainstorming 11.10.2017

### ISSUE THREAD

**Issue by jcebel** [jcolladosp/ePills#1]
Can you add the results of the Brainstorming under this issue? 
Or should we rather open Google Docs for that?

**Comment by deRemo** [comment]
Maybe Google Docs is clearer

2017-10-11 16:22 GMT+01:00 Jonas Ebel <notifications@github.com>:

**Comment by deRemo** [comment]
Anyway i will do it later today or tomorrow, i'm busy right now!

**Comment by jcebel** [comment]
I'll create one google team space for that.
Yeah no worries!
