### ISSUE TITLE
Picture Storage

### ISSUE THREAD

**Issue by jcebel** [jcolladosp/ePills#2]
Any opinions on the place we store the pictures?
We can either store it in a private directory, which gives only our access implicit access 
Or we can store it publicly - so the gallery application and others have a direct access.

Any thoughts on that?
I will for now go with the private directory.

**Comment by jcolladosp** [comment]
Whaterver work, but I would go for the public one. I think most apps use that option.

**Comment by jcebel** [comment]
Decided to use app - internal storage, so the pictures can't be deleted from the outside.
